<script>
    //异步函数可以有返回值，但是不管返回什么普通值，都会包裹在Promise.then中
    async function foo(){
        console.log("hello async函数")
        
        //(1)返回普通值，promise是成功的promise
        //return 123

        //(2)异步函数自己返回了promise,得到的Promise状态由这个promise决定
       // return new Promise((resolve,reject)=>{
       //     resolve("宝宝")
       //     reject("没钱")
       // })

       //(3) 异步函数返回值是一个对象并且实现thenable，得到promise状态由thenable决定
       //return {
       // then(resolve,reject){
       //     reject("没钱")
       // }
       //}

       //(4) 在async中抛出一个错误，得到的promise是一个失败的promise
       throw new Error("我是一个错误")
    }
    
    foo().then(res=>{
        console.log("res:",res)
    }).catch(err=>{
        console.log("err:",err)
    })
</script>